### ISSUE TITLE
how to debug?

### ISSUE THREAD

**Issue by Luuk34** [lesander/fritzbox.js#11]
I am always getting this:
`D:\TEMP\fritz\node_modules\fritzbox.js\test>node phonebook.js
Error:  Error: connect ECONNREFUSED 192.168.1.1:443`

I did change username/password, 
I did check if I can logon with this username/password
I even did set 'debug' to true

(and, yes, I am pretty new to **node**)

**Comment by Luuk34** [comment]
Any clues? not even an 'not aporpriate' here ?

**Comment by lesander** [comment]
Hi there Luuk, my apologies for the late reply. A busy life comes with consequences, I fear I've neglected my open-source projects for some time. 

The error you're getting basically says that FritzBox.js can't connect to your fritzbox with the given settings. Is HTTPS/SSL enabled on your fritzbox and are you sure the given IP address is correct?

**Comment by ametama** [comment]
Which username and password should I assign to the options object? "Admin" and the password for the fritz.box screen didn't seem to work. I am getting the same error as Luuk.

Edit: I fixed the issue by changing my TCP https port of the fritz.box to 443.

**Comment by Luuk34** [comment]
I got it working

`const fritz = require('fritzbox.js')
const options = {
  username: 'luuk',
  password: '......',
  server: 'fritz.box:40443',
  protocol: 'https' }


var item = 'CALLHISTORY';
fritz.getCalls(options)
.then((callHistory) => {
  if (callHistory.error) return console.log(callHistory.error.message)
	{
		if (item!="") { console.log(item); item="" }
		  console.log(callHistory)
	}
})`

Under Fritzbox/Internet/PremitAccess/FritzboxServices, port 40443 is defined.
User is defined under System/FritzboxUsers
