### ISSUE TITLE
Incoming call?

### ISSUE THREAD

**Issue by KLVN** [lesander/fritzbox.js#2]
Is it possible to retrieve an event like `onIncomingCall` and trigger an action if it occurs?

Thanks,
KLVN

**Comment by lesander** [comment]
Hi Kevin,

This feature can certainly be added! I will investigate what our options are. Thank you for the request!

-- Sander

**Comment by lesander** [comment]
Until I have this implemented in FritzBox.js, you could use `fritzbox-callmonitor` by Thorsten Basse. 
https://github.com/tbasse/fritzbox-callmonitor

**Comment by KLVN** [comment]
Thanks for adding it to the milestone and the suggestion.

**Comment by lesander** [comment]
A call monitor has been implemented in v2.0.0.
